"""Noninteractive, data-preserving startup for the pinned meme ORM dependency.

Upstream's development-mode sync can rebuild tables on a migration error. Use
its versioned migrations instead; adopt an old sync-created database only when
its complete schema already matches the loaded models.
"""

import asyncio
import sqlite3
from argparse import Namespace
from datetime import datetime, timezone
from pathlib import Path

from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext
from click import UsageError
from nonebot.log import logger
from sqlalchemy import inspect
from sqlalchemy.util import greenlet_spawn


def backup_sqlite(database: Path) -> Path:
    destination_dir = database.parent / "backups"
    destination_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    destination = destination_dir / f"{database.stem}.pre-migration-{timestamp}.sqlite3"
    # SQLite's online backup API includes committed WAL data as well.
    with sqlite3.connect(database.resolve().as_uri() + "?mode=ro", uri=True) as source:
        with sqlite3.connect(destination) as target:
            source.backup(target)
    return destination


def _schema_state(connection, metadata) -> tuple[bool, bool, bool]:
    context = MigrationContext.configure(connection)
    tables = set(inspect(connection).get_table_names()) - {"alembic_version"}
    return bool(context.get_current_heads()), bool(tables), not compare_metadata(context, metadata)


async def initialize_meme_orm() -> None:
    import nonebot_plugin_orm as orm
    from nonebot_plugin_orm import migrate
    from nonebot_plugin_orm.exception import AutogenerateDiffsDetected
    from nonebot_plugin_orm.utils import StreamToLogger

    # This compatibility module is tested with and pins nonebot-plugin-orm 0.8.3.
    orm._init_orm()
    options = Namespace(cmd=(migrate.check, [], []))
    with migrate.AlembicConfig(stdout=StreamToLogger(), cmd_opts=options) as config:
        try:
            await greenlet_spawn(migrate.check, config)
            return
        except (UsageError, AutogenerateDiffsDetected):
            pass

        states = []
        for name, engine in orm._engines.items():
            async with engine.connect() as connection:
                states.append(await connection.run_sync(_schema_state, orm._metadatas[name]))

        unversioned_existing = [state for state in states if not state[0] and state[1]]
        if unversioned_existing and (
            len(unversioned_existing) != len(states) or not all(state[2] for state in states)
        ):
            raise RuntimeError(
                "新版表情数据库已有数据但没有迁移版本，且表结构不匹配；"
                "已停止自动迁移并保留原数据，请检查数据库结构。"
            )

        backed_up: set[Path] = set()
        for engine in orm._engines.values():
            if engine.url.get_backend_name() != "sqlite" or not engine.url.database:
                continue
            database = Path(engine.url.database).resolve()
            if database.is_file() and database not in backed_up:
                backup = await asyncio.to_thread(backup_sqlite, database)
                logger.info("Meme database backup created: {}", backup.name)
                backed_up.add(database)

        if unversioned_existing:
            # No DDL or data migration: this database is already at the target
            # schema, created by the previous development-mode startup.
            options.cmd = (migrate.stamp, ["revisions"], [])
            await greenlet_spawn(migrate.stamp, config, ("heads",))
        else:
            options.cmd = (migrate.upgrade, ["revision"], [])
            await greenlet_spawn(migrate.upgrade, config)
        options.cmd = (migrate.check, [], [])
        await greenlet_spawn(migrate.check, config)
        logger.info("Meme database migrations verified; no interactive input required")


def install_meme_orm_startup(driver) -> None:
    import nonebot_plugin_orm as orm

    # NoneBot has no public unregister-startup API. Replace only this exact
    # dependency hook, leaving all other plugins and their ordering intact.
    startup_functions = driver._lifespan._startup_funcs
    if initialize_meme_orm in startup_functions:
        return
    matches = [
        index for index, callback in enumerate(startup_functions) if callback is orm.init_orm
    ]
    if len(matches) != 1:
        raise RuntimeError("Cannot locate the meme ORM startup hook; check dependency versions")
    startup_functions[matches[0]] = initialize_meme_orm
